name: "Accession Tracker"
description: Track sample batch from arrival to completion
title: "[Task]: add task title "
labels: ["task"]
projects: ["Genetics Lab Management"]
assignees: 
  - AlainaHarmon
body:
  -type: textarea
  id: title
    attributes:
      label: Batch Description
      description: Provide an overview of the samples, including anticipated sample number.
      placehold: E.g. St. Croix nesting leatherbacks collected 2023-2025. 500 samples.

    - type: textarea
    id: contact
    attributes:
      label: Main Non-SWFSC Contact
      description: List name and organization of the main person able to answer questions about the samples.
      placeholder: E.g. Kelly Stewart, SWFSC

    - type: textarea
    id: location
    attributes:
      label: Temporary Storage Location
      description: Provide a link to the working files on the network and the CITES files on Google Shared Drives.
      Describe where the samples are located and what their storage container looks like.
      placeholder: E.g. White cryobox in F6 bottom 1/2, top shelf.

    - type: markdown
         value: |
       ## Batch Data
       1. If a priority batch, star the repo. 
       2. Format the issue name as a descriptive title followed by a turtle or mammal emoji
       3. Comment out dates of step completions.

    - type: checkboxes
    id: subtasks
    attributes:
      label: ✅ Progress
      description: List of subtasks and their assignees (you can edit this list)
      options:
        - label: Package Received: Comment date received when complete. Add to database Shipment table. Add temporary storage location to text about this sample batch. — _@AlainaHarmon_ 
        - label: Data Received — _@AlainaHarmon_
        - label: Inventoried — _@AlainaHarmon_
        - label: Data Verified: Sample questions answered — _@AlainaHarmon_
        - label: Permits Acquired — _@AlainaHarmon_
        - label: Locations Assigned in Location Sheet — _@AlainaHarmon_
        - label: Accessioned: Data cleaned and imported into database — _@AlainaHarmon_
        - label: T and Lab IDs Added to ID Tracker — _@AlainaHarmon_
        - label: Labels Printed — _@AlainaHarmon_
        - label: Labeled — _@AlainaHarmon_
        - label: Subsample — _@AlainaHarmon_
        - label: Transferred Containers — _@AlainaHarmon_
        - label: Refilled — _@AlainaHarmon_
        - label: Records Scanned — _@AlainaHarmon_
        - label: Files Filed: All archival files in appropriate folder on network. All files linked in database. — _@AlainaHarmon_
        - label: Turtles Only: To Archive Turtles file added to folder for Erin — _@AlainaHarmon_
        - label: Turtles Only: Update Flipper Tracker if relevant — _@AlainaHarmon_
        - label: MMGP or MTGP Accessioned Email Sent — _@AlainaHarmon_ 
        - label: Sample Analysis Requests Assigned — _@AlainaHarmon_
        - label: Contributor Emailed List of IDs — _@AlainaHarmon_
        - label: Put Away in Long-Term Storage: If partially put away, comment what was put away and what date. — _@AlainaHarmon_

    - type: input
    id: labels
    attributes:
      label: 🗂 Suggested Labels
      description: Add MMGP or MTGP, Priority Batch if priority, Species, and Country of Origin
      placeholder: e.g. MTGP, Priority Batch, Leatherbacks, Virgin Islands U.S.




