name: "Accession Tracker"
description: Track sample batch from arrival to completion
title: "[Task]: add task title "
projects: ["SWFSC-MMTD-Genetics/2"]
  - url: https://github.com/orgs/SWFSC-MMTD-Genetics/projects/2
assignees: 
  - AlainaHarmon
body:
- type: markdown
  attributes:
       value: | 
         "## Batch Data
         1. If a priority batch, star the repo before the title text. You can pull up emojis by right clicking in the title text box.
         2. Format the issue name as a descriptive title followed by a turtle or mammal emoji.
         3. Comment out dates of step completions.
         4. Add labels "MMGP" or "MTGP" and species and country of origin.
  
- type: textarea
  id: title
  attributes:
      label: Batch Description
      description: Provide an overview of the samples, including anticipated sample number.
      placeholder: E.g. St. Croix nesting leatherbacks collected 2023-2025. 500 samples.

- type: textarea
  id: contact
  attributes:
      label: Main Non-SWFSC Contact
      description: List name and organization of the main person able to answer questions about the samples.
      placeholder: E.g. Jim Reilly, Wildlife Organization

- type: textarea
  id: location
  attributes:
      label: Temporary Storage Location
      description: Provide a link to the working files on the network and the CITES files on Google Shared Drives. Describe where the samples are located and what their storage container looks like.
      placeholder: E.g. White cryobox in F6 bottom 1/2, top shelf. Files at [paste network location].

- type: checkboxes
  id: subtasks
  attributes:
      label: ✅ Progress
      description: List of subtasks and their assignees
      options:
        - label: Package Received. Comment date received when complete. Add temporary storage location to text about this sample batch.
        - label: Add to database Shipment table.  
        - label: Data Received 
        - label: Inventoried 
        - label: Data Verified. Sample questions answered.
        - label: Permits Acquired 
        - label: Locations Assigned in Location Sheet
        - label: Accessioned. Data cleaned and imported into database.
        - label: T and Lab IDs Added to ID Tracker
        - label: Labels Printed
        - label: Labeled
        - label: Subsampled
        - label: Transferred Containers
        - label: Refilled
        - label: Records Scanned
        - label: Files Filed. All archival files in appropriate folder on network. All files linked in database.
        - label: Turtles Only. To Archive Turtles file added to folder for Erin.
        - label: Turtles Only. Update Flipper Tracker if relevant.
        - label: MMGP or MTGP Accessioned Email Sent 
        - label: Mammals Only. Sample Analysis Requests Assigned
        - label: Contributor Emailed List of IDs
        - label: Put Away in Long-Term Storage. If partially put away, comment what was put away and what date.

- type: input
  id: labels
  attributes:
      label: 🗂 Suggested Labels
      description: Add MMGP or MTGP, Priority Batch if priority, Species, and Country of Origin
      placeholder: e.g. MTGP, Priority Batch, Leatherbacks, Virgin Islands U.S.




