# This code acts on AlainaTest.yml, taking the dropdown at the end of the form, and assigning 
# a Label to the issue based on the selection in the dropdown.
name: Issue labeler
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

      # only required for workflows in private repositories
      # actions: read
      # contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/AlainaTest.yml
          # change template-path to the name of your .yml file containing the dropdown

      - name: Set labels based on dropdown
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: program
          # change section to the id attribute you use for your dropdown
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}
